openapi: 3.0.3
info:
  title: RandomStoreServer
  description: API spec that shows all relevant endpoints and operations it can perform
  version: 0.1.1
  contact:
    name: Edson Manuel Carballo Vera
    email: edsonmanuelcarballovera@gmail.com
    url: https://twitter.com/EdsonManuelVera
servers:
  - description: Production and testing server (for a while)
    url: 'http:clayrite.ddns.net:42101'
paths:
  /login:
    $ref: "./login.yml"
  /users:
    $ref: "./users.yml"
  /storage/{storage_name}:
    $ref: "./storage_name.yml"
  /storage/json/{storage_name}:
    $ref: "./json_storage_name.yml"
  /storage/csv/{storage_name}:
    $ref: "./csv_storage_name.yml"
